management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console