management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:h2:file:./data/mydatabase
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      id:
        new_generator_mappings: false
      use-new-id-generator-mappings: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
